spring:
  data:
    mongodb:
      uri: mongodb+srv://nidhisharma00200:28november2004@cluster0.qxefjgv.mongodb.net/<your_database>
      database: journaldb
      auto-index-creation: true


server:
  port: 8080
